backend:
  name: github
  repo: TrnsltLife/Art-of-Solomon-Museum-CMS-Data
  branch: main
  #base_url: 
  #auth_endpoint: auth

local_backend: true

media_folder: "content/artifacts/media"
public_folder: "/content/artifacts/media"

collections:
  - name: "artifacts"
    label: "Artifacts"
    folder: "content/artifacts"
    create: true
    slug: "{{fields.artifact_name}}"
    path: "{{slug}}/index"
    format: "frontmatter"
    extension: "md"
    media_folder: ""
    public_folder: ""
    summary: "{{artifact_name}} - {{title}} {{subitle}}"

    fields:
      - { label: "Artifact Name", name: "artifact_name", widget: "string", required: true, hint: "ArtistLastName-TitleAbbreviation-YearCreated, e.g. Zonia-Arise-1975, Preyzner-Cantiques-1977" }
      - { label: "Accession Number", name: "accession_number", widget: "string", required: false, hint: "Year.Number, e.g. 2026.001"}
      - label: "Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Aromatic", value: "aromatic" }
          - { label: "Book", value: "book" }
          - { label: "Furniture", value: "furniture" }
          - { label: "Painting", value: "painting" }
          - { label: "Plant", value: "plant" }
          - { label: "Print", value: "print" }
          - { label: "Sculpture", value: "sculpture" }
          - { label: "Tapestry", value: "tapestry" }
        allow_add: false
        required: false
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Year Created", name: "year_created", widget: "string", required: false }
      - { label: "Location Created", name: "location_created", widget: "string", required: false }
      - { label: "Limitation Statement", name: "limitation_statement", widget: "markdown", required: false }
      #- { label: "Medium", name: "medium", widget: "string", required: false }
      #- { label: "Provenance", name: "provenance", widget: "text", required: false }
      - label: "Contributors"
        name: "contributors"
        required: true
        widget: "list"
        summary: "{{fields.name}} â€” {{fields.role}}"
        fields:
          - label: "Name"
            name: "name"
            required: false
            widget: "string"

          - label: "Role"
            name: "role"
            required: true
            widget: "select"
            options:
              - { label: "Artist", value: "artist" }
              - { label: "Anonymous", value: "anonymous" }
              - { label: "Author", value: "author" }
              - { label: "Editor", value: "editor" }
              - { label: "Font Design", value: "font_design" }
              - { label: "Publisher", value: "publisher" }
              - { label: "Translator", value: "translator" }
            allow_add: false
      - label: "Artifact Images"
        name: "images"
        required: false
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Type"
            name: "type"
            widget: "select"
            options:
              - { label: "Back Cover", value: "back_cover" }
              - { label: "Cover", value: "cover" }
              - { label: "Detail", value: "detail" }
              - { label: "Main", value: "main" }
              - { label: "Page", value: "page" }
              - { label: "Spine", value: "spine" }
            allow_add: false
          - label: "Interpretations"
            name: "interpretations"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Tags", name: "tags", widget: "string", required: false }
